// frontend/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  Classroom, User, UserRole, Quiz, Assignment,
  WardSubmission, AssignmentSubmission, AttendanceRecord
} from './types';
import { ApiService } from './services/api.service';

// Components
import { HeaderComponent } from './components/header/header.component';
import { LoginPageComponent } from './components/login-page/login-page.component';
import { SpinnerIconComponent } from './components/icons/spinner-icon.component';
import { ClassroomListComponent } from './components/classroom-list/classroom-list.component';
import { TutorDashboardComponent } from './components/tutor-dashboard/tutor-dashboard.component';
import { WardDashboardComponent } from './components/ward-dashboard/ward-dashboard.component';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [
    CommonModule,
    HeaderComponent,
    LoginPageComponent,
    SpinnerIconComponent,
    ClassroomListComponent,
    TutorDashboardComponent,
    WardDashboardComponent
  ],
  template: `
    <div class="min-h-screen bg-slate-50 dark:bg-slate-900 text-slate-900 dark:text-slate-200 font-sans">
      <app-header [isAuthenticated]="!!currentUser" (logout)="handleLogout()"></app-header>
      <main class="container mx-auto p-4 sm:p-6 lg:p-8">
        <div *ngIf="isAuthLoading" class="flex justify-center items-center h-screen">
          <app-spinner-icon [className]="'w-10 h-10'"></app-spinner-icon>
        </div>

        <ng-container *ngIf="!isAuthLoading">
          <app-login-page *ngIf="!currentUser" (login)="handleLogin($event)" (register)="handleRegister($event)"></app-login-page>
          
          <ng-container *ngIf="currentUser">
            <div *ngIf="isLoading" class="flex justify-center items-center h-[calc(100vh-10rem)]">
              <app-spinner-icon [className]="'w-10 h-10'"></app-spinner-icon>
            </div>

            <ng-container *ngIf="!isLoading">
              <app-classroom-list 
                *ngIf="!selectedClassroom"
                [classrooms]="classrooms"
                [currentUser]="currentUser"
                (selectClassroom)="setSelectedClassroomId($event)"
                (createClassroom)="handleCreateClassroom($event)"
                (joinClassroom)="handleJoinClassroom($event)">
              </app-classroom-list>
              
              <app-tutor-dashboard
                *ngIf="selectedClassroom && currentUser.role === userRoleEnum.Tutor"
                [classroom]="selectedClassroom"
                [allWards]="allWards"
                (back)="setSelectedClassroomId(null)"
                (quizCreated)="handleQuizCreated($event)"
                (assignmentCreated)="handleAssignmentCreated($event)"
                (updateAttendance)="handleUpdateAttendance($event)"
                (approveRequest)="handleApproveRequest($event)"
                (gradeAssignment)="handleGradeAssignment($event)">
              </app-tutor-dashboard>
              
              <app-ward-dashboard
                *ngIf="selectedClassroom && currentUser.role === userRoleEnum.Ward"
                [classroom]="selectedClassroom"
                [currentUser]="currentUser"
                (quizCompleted)="handleQuizCompleted($event)"
                (assignmentSubmitted)="handleAssignmentSubmitted($event)"
                (back)="setSelectedClassroomId(null)">
              </app-ward-dashboard>
            </ng-container>
          </ng-container>
        </ng-container>
      </main>
    </div>
  `,
})
export class AppComponent implements OnInit {
  currentUser: User | null = null;
  classrooms: Classroom[] = [];
  allWards: User[] = [];
  selectedClassroomId: string | null = null;
  isLoading = false;
  isAuthLoading = true;
  userRoleEnum = UserRole;

  constructor(private apiService: ApiService) {}

  ngOnInit(): void {
    const token = localStorage.getItem('token');
    const user = localStorage.getItem('user');
    if (token && user) {
        try {
            this.currentUser = JSON.parse(user);
        } catch (e) {
            this.handleLogout();
        }
    }
    this.isAuthLoading = false;
    if (this.currentUser) {
      this.fetchData();
    }
  }

  get selectedClassroom(): Classroom | undefined {
    return this.classrooms.find(c => c.id === this.selectedClassroomId);
  }

  fetchData(): void {
    this.isLoading = true;
    this.apiService.fetchInitialData().subscribe({
        next: data => {
            this.classrooms = data.classrooms;
            this.allWards = data.allWards;
            this.isLoading = false;
        },
        error: error => {
            console.error("Failed to fetch initial data:", error);
            this.handleLogout();
            this.isLoading = false;
        }
    });
  }

  private updateClassroomState(updatedClassroom: Classroom): void {
    const index = this.classrooms.findIndex(c => c.id === updatedClassroom.id);
    if (index > -1) {
      this.classrooms[index] = updatedClassroom;
      this.classrooms = [...this.classrooms];
    }
  }

  handleLogin({ name, pass }: { name: string, pass: string }): void {
    this.apiService.login(name, pass).subscribe({
      next: ({ user }) => {
        localStorage.setItem('user', JSON.stringify(user));
        this.currentUser = user;
        this.fetchData();
      },
      error: error => {
        console.error(error);
        alert(error.message || 'Login failed.');
      }
    });
  }

  handleRegister({ name, pass, role }: { name: string, pass: string, role: UserRole }): void {
    this.apiService.register(name, pass, role).subscribe({
      next: ({ user }) => {
        localStorage.setItem('user', JSON.stringify(user));
        this.currentUser = user;
        if (role === UserRole.Ward) {
          this.allWards = [...this.allWards, user];
        }
        this.fetchData();
      },
      error: error => {
        console.error(error);
        alert(error.message || 'Registration failed.');
      }
    });
  }

  handleLogout(): void {
      localStorage.removeItem('token');
      localStorage.removeItem('user');
      this.currentUser = null;
      this.selectedClassroomId = null;
      this.classrooms = [];
      this.allWards = [];
  }

  setSelectedClassroomId(id: string | null): void {
    this.selectedClassroomId = id;
  }

  handleCreateClassroom({ name, description }: { name: string, description: string }): void {
    this.apiService.createClassroom(name, description).subscribe({
      next: newClassroom => {
        this.classrooms = [...this.classrooms, newClassroom];
      },
      error: error => {
        console.error(error);
        alert(error.message || 'Failed to create classroom.');
      }
    });
  }

  handleJoinClassroom(code: string): void {
    this.apiService.joinClassroom(code).subscribe({
      next: () => {
        alert("Join request sent to the tutor for approval.");
        this.fetchData(); // Refresh data to see pending request if applicable
      },
      error: error => {
        console.error(error);
        alert(error.message || 'Failed to join classroom.');
      }
    });
  }

  handleApproveRequest(wardId: string): void {
    if (this.selectedClassroomId) {
      this.apiService.approveJoinRequest(this.selectedClassroomId, wardId).subscribe({
        next: updatedClassroom => this.updateClassroomState(updatedClassroom),
        error: error => console.error(error)
      });
    }
  }
  
  handleQuizCreated(quizData: Omit<Quiz, 'id' | 'submissions'>): void {
    if (this.selectedClassroomId) {
      this.apiService.addQuizToClassroom(this.selectedClassroomId, quizData).subscribe({
        next: updatedClassroom => this.updateClassroomState(updatedClassroom),
        error: error => console.error(error)
      });
    }
  }
  
  handleAssignmentCreated(assignmentData: Omit<Assignment, 'id'|'submissions'>): void {
    if (this.selectedClassroomId) {
      this.apiService.addAssignmentToClassroom(this.selectedClassroomId, assignmentData).subscribe({
        next: updatedClassroom => this.updateClassroomState(updatedClassroom),
        error: error => console.error(error)
      });
    }
  }

  handleQuizCompleted({ quizId, submission }: { quizId: string, submission: Omit<WardSubmission, 'wardId'> }): void {
    if (this.selectedClassroomId) {
      this.apiService.submitQuiz(this.selectedClassroomId, quizId, submission).subscribe({
        next: updatedClassroom => this.updateClassroomState(updatedClassroom),
        error: error => console.error(error)
      });
    }
  }

  handleAssignmentSubmitted({ assignmentId, submission }: { assignmentId: string, submission: Omit<AssignmentSubmission, 'wardId'> }): void {
    if (this.selectedClassroomId) {
      this.apiService.submitAssignment(this.selectedClassroomId, assignmentId, submission).subscribe({
        next: updatedClassroom => this.updateClassroomState(updatedClassroom),
        error: error => console.error(error)
      });
    }
  }
  
  handleGradeAssignment({ assignmentId, wardId, grade, feedback }: { assignmentId: string, wardId: string, grade: number, feedback: string }): void {
      if (this.selectedClassroomId) {
        this.apiService.gradeAssignment(this.selectedClassroomId, assignmentId, wardId, grade, feedback).subscribe({
          next: updatedClassroom => this.updateClassroomState(updatedClassroom),
          error: error => console.error(error)
        });
      }
  }

  handleUpdateAttendance(record: AttendanceRecord): void {
    if (this.selectedClassroomId) {
      this.apiService.updateAttendance(this.selectedClassroomId, record).subscribe({
        next: updatedClassroom => this.updateClassroomState(updatedClassroom),
        error: error => console.error(error)
      });
    }
  }
}

<!-- This file is not used as the template is defined inline in the component TypeScript file. -->

// App.tsx

import React, { useState, useEffect, useCallback } from 'react';
import { Classroom, User, UserRole, Ward, WardSubmission, AssignmentSubmission, Quiz, Assignment, AttendanceRecord } from './types';
import { 
    apiLogin, apiRegister, apiFetchInitialData, apiCreateClassroom, apiJoinClassroom, 
    apiApproveJoinRequest, apiAddQuizToClassroom, apiAddAssignmentToClassroom,
    apiSubmitQuiz, apiSubmitAssignment, apiGradeAssignment, apiUpdateAttendance 
} from './services/apiService';
import LoginPage from './components/LoginPage';
import Header from './components/Header';
import ClassroomList from './components/ClassroomList';
import TutorDashboard from './components/TutorDashboard';
import WardDashboard from './components/WardDashboard';
import SpinnerIcon from './components/icons/SpinnerIcon';

const App: React.FC = () => {
  const [currentUser, setCurrentUser] = useState<User | null>(null);
  const [classrooms, setClassrooms] = useState<Classroom[]>([]);
  const [allWards, setAllWards] = useState<User[]>([]);
  const [selectedClassroomId, setSelectedClassroomId] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [isAuthLoading, setIsAuthLoading] = useState(true);

  // Check for existing token on initial load
  useEffect(() => {
    const token = localStorage.getItem('token');
    const user = localStorage.getItem('user');
    if (token && user) {
        try {
            setCurrentUser(JSON.parse(user));
        } catch (e) {
            // Clear invalid data
            localStorage.removeItem('token');
            localStorage.removeItem('user');
        }
    }
    setIsAuthLoading(false);
  }, []);

  // Fetch data when user logs in
  useEffect(() => {
    const fetchData = async () => {
        if (currentUser) {
            setIsLoading(true);
            try {
                const data = await apiFetchInitialData();
                setClassrooms(data.classrooms);
                setAllWards(data.allWards);
            } catch (error) {
                console.error("Failed to fetch initial data:", error);
                // Handle token expiration - log user out
                handleLogout();
            } finally {
                setIsLoading(false);
            }
        }
    };
    fetchData();
  }, [currentUser]);
  
  const updateClassroomState = (updatedClassroom: Classroom) => {
    setClassrooms(prev => prev.map(c => c.id === updatedClassroom.id ? updatedClassroom : c));
  };

  const handleLogin = async (name: string, pass: string): Promise<boolean> => {
    try {
      const { user } = await apiLogin(name, pass);
      localStorage.setItem('user', JSON.stringify(user));
      setCurrentUser(user);
      return true;
    } catch (error) {
      console.error(error);
      return false;
    }
  };

  const handleRegister = async (name: string, pass: string, role: UserRole): Promise<boolean> => {
    try {
      const { user } = await apiRegister(name, pass, role);
      localStorage.setItem('user', JSON.stringify(user));
      setCurrentUser(user);
      if (role === UserRole.Ward) {
        setAllWards(prev => [...prev, user]);
      }
      return true;
    } catch (error) {
      console.error(error);
      return false;
    }
  };
  
  const handleLogout = () => {
      localStorage.removeItem('token');
      localStorage.removeItem('user');
      setCurrentUser(null);
      setSelectedClassroomId(null);
      setClassrooms([]);
      setAllWards([]);
  };

  const handleCreateClassroom = async (name: string, description: string) => {
    try {
      const newClassroom = await apiCreateClassroom(name, description);
      setClassrooms(prev => [...prev, newClassroom]);
    } catch (error) { console.error(error); }
  };

  const handleJoinClassroom = async (code: string) => {
    try {
      await apiJoinClassroom(code);
      alert("Join request sent to the tutor for approval.");
    } catch (error) { 
        console.error(error);
        alert((error as Error).message);
    }
  };

  const handleApproveRequest = async (wardId: string) => {
    if (selectedClassroomId) {
      try {
        const updatedClassroom = await apiApproveJoinRequest(selectedClassroomId, wardId);
        updateClassroomState(updatedClassroom);
      } catch (error) { console.error(error); }
    }
  };
  
  const handleQuizCreated = async (quizData: Omit<Quiz, 'id' | 'submissions'>) => {
    if (selectedClassroomId) {
      try {
        const updatedClassroom = await apiAddQuizToClassroom(selectedClassroomId, quizData);
        updateClassroomState(updatedClassroom);
      } catch (error) { console.error(error); }
    }
  };
  
  const handleAssignmentCreated = async (assignmentData: Omit<Assignment, 'id'|'submissions'>) => {
    if (selectedClassroomId) {
      try {
        const updatedClassroom = await apiAddAssignmentToClassroom(selectedClassroomId, assignmentData);
        updateClassroomState(updatedClassroom);
      } catch (error) { console.error(error); }
    }
  };

  const handleQuizCompleted = async (quizId: string, submission: Omit<WardSubmission, 'wardId'>) => {
    if (selectedClassroomId) {
      try {
        const updatedClassroom = await apiSubmitQuiz(selectedClassroomId, quizId, submission);
        updateClassroomState(updatedClassroom);
      } catch (error) { console.error(error); }
    }
  };

  const handleAssignmentSubmitted = async (assignmentId: string, submission: Omit<AssignmentSubmission, 'wardId'>) => {
    if (selectedClassroomId) {
      try {
        const updatedClassroom = await apiSubmitAssignment(selectedClassroomId, assignmentId, submission);
        updateClassroomState(updatedClassroom);
      } catch (error) { console.error(error); }
    }
  };
  
  const handleGradeAssignment = async (assignmentId: string, wardId: string, grade: number, feedback: string) => {
      if (selectedClassroomId) {
          try {
            const updatedClassroom = await apiGradeAssignment(selectedClassroomId, assignmentId, wardId, grade, feedback);
            updateClassroomState(updatedClassroom);
          } catch (error) { console.error(error); }
      }
  }

  const handleUpdateAttendance = async (record: AttendanceRecord) => {
    if (selectedClassroomId) {
      try {
        const updatedClassroom = await apiUpdateAttendance(selectedClassroomId, record);
        updateClassroomState(updatedClassroom);
      } catch (error) { console.error(error); }
    }
  };

  const selectedClassroom = classrooms.find(c => c.id === selectedClassroomId);

  const renderContent = () => {
    if (isAuthLoading) {
      return <div className="flex justify-center items-center h-screen"><SpinnerIcon className="w-10 h-10" /></div>;
    }
    
    if (!currentUser) {
      return <LoginPage onLogin={handleLogin} onRegister={handleRegister} />;
    }
    
    if (isLoading) {
        return <div className="flex justify-center items-center h-[calc(100vh-10rem)]"><SpinnerIcon className="w-10 h-10" /></div>;
    }

    if (!selectedClassroom) {
      return <ClassroomList 
        classrooms={classrooms} 
        currentUser={currentUser} 
        onSelectClassroom={setSelectedClassroomId}
        onCreateClassroom={handleCreateClassroom}
        onJoinClassroom={handleJoinClassroom}
      />;
    }

    if (currentUser.role === UserRole.Tutor) {
      return <TutorDashboard 
        classroom={selectedClassroom} 
        allWards={allWards}
        onBack={() => setSelectedClassroomId(null)} 
        onQuizCreated={handleQuizCreated}
        onAssignmentCreated={handleAssignmentCreated}
        onUpdateAttendance={handleUpdateAttendance}
        onApproveRequest={handleApproveRequest}
        onGradeAssignment={handleGradeAssignment}
      />;
    }
    
    if (currentUser.role === UserRole.Ward) {
        return <WardDashboard 
            classroom={selectedClassroom}
            currentUser={currentUser}
            onQuizCompleted={handleQuizCompleted}
            onAssignmentSubmitted={handleAssignmentSubmitted}
            onBack={() => setSelectedClassroomId(null)}
        />
    }
  };

  return (
    <div className="min-h-screen bg-slate-50 dark:bg-slate-900 text-slate-900 dark:text-slate-200 font-sans">
      <Header isAuthenticated={!!currentUser} onLogout={handleLogout} />
      <main className="container mx-auto p-4 sm:p-6 lg:p-8">
        {renderContent()}
      </main>
    </div>
  );
};

export default App;
