// frontend/src/app/components/create-classroom-modal/create-classroom-modal.component.ts
import { Component, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-create-classroom-modal',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './create-classroom-modal.component.html',
})
export class CreateClassroomModalComponent {
  @Output() close = new EventEmitter<void>();
  @Output() create = new EventEmitter<{name: string, description: string}>();

  name = '';
  description = '';
  error: string | null = null;

  handleSubmit(): void {
    if (!this.name.trim() || !this.description.trim()) {
      this.error = 'Name and description are required.';
      return;
    }
    this.error = null;
    this.create.emit({ name: this.name, description: this.description });
  }
}

<div class="fixed inset-0 bg-black bg-opacity-50 flex justify-center items-center z-50 p-4">
    <div class="bg-white dark:bg-slate-800 rounded-lg shadow-xl p-6 w-full max-w-lg">
      <div class="flex justify-between items-center mb-4">
        <h2 class="text-2xl font-bold text-slate-800 dark:text-white">Create New Classroom</h2>
        <button (click)="close.emit()" class="text-slate-400 hover:text-slate-600 dark:hover:text-slate-200">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>
  
      <div class="space-y-4">
        <div>
          <label for="className" class="block text-sm font-medium text-slate-700 dark:text-slate-300">Classroom Name</label>
          <input
            type="text"
            id="className"
            [(ngModel)]="name"
            class="mt-1 block w-full px-3 py-2 bg-white dark:bg-slate-700 border border-slate-300 dark:border-slate-600 rounded-md shadow-sm"
            placeholder="e.g., Grade 11 Physics"
          />
        </div>
        <div>
          <label for="classDescription" class="block text-sm font-medium text-slate-700 dark:text-slate-300">Description</label>
          <textarea
            id="classDescription"
            rows="3"
            [(ngModel)]="description"
            class="mt-1 block w-full px-3 py-2 bg-white dark:bg-slate-700 border border-slate-300 dark:border-slate-600 rounded-md shadow-sm"
            placeholder="A brief overview of the classroom's subject."
          ></textarea>
        </div>
        <p *ngIf="error" class="text-red-500 text-sm">{{ error }}</p>
      </div>
  
      <div class="mt-6 flex justify-end space-x-3">
        <button (click)="close.emit()" class="px-4 py-2 border border-slate-300 text-sm font-medium rounded-md">
          Cancel
        </button>
        <button (click)="handleSubmit()" class="px-4 py-2 border border-transparent text-sm font-medium rounded-md shadow-sm text-white bg-sky-600 hover:bg-sky-700">
          Create Classroom
        </button>
      </div>
    </div>
</div>

// components/CreateClassroomModal.tsx
import React, { useState } from 'react';

interface CreateClassroomModalProps {
  onClose: () => void;
  onCreate: (name: string, description: string) => void;
}

const CreateClassroomModal: React.FC<CreateClassroomModalProps> = ({ onClose, onCreate }) => {
  const [name, setName] = useState('');
  const [description, setDescription] = useState('');
  const [error, setError] = useState<string | null>(null);

  const handleSubmit = () => {
    if (!name.trim() || !description.trim()) {
      setError('Name and description are required.');
      return;
    }
    setError(null);
    onCreate(name, description);
  };

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex justify-center items-center z-50 p-4">
      <div className="bg-white dark:bg-slate-800 rounded-lg shadow-xl p-6 w-full max-w-lg">
        <div className="flex justify-between items-center mb-4">
          <h2 className="text-2xl font-bold text-slate-800 dark:text-white">Create New Classroom</h2>
          <button onClick={onClose} className="text-slate-400 hover:text-slate-600 dark:hover:text-slate-200">
            <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>

        <div className="space-y-4">
          <div>
            <label htmlFor="className" className="block text-sm font-medium text-slate-700 dark:text-slate-300">Classroom Name</label>
            <input
              type="text"
              id="className"
              value={name}
              onChange={(e) => setName(e.target.value)}
              className="mt-1 block w-full px-3 py-2 bg-white dark:bg-slate-700 border border-slate-300 dark:border-slate-600 rounded-md shadow-sm"
              placeholder="e.g., Grade 11 Physics"
            />
          </div>
          <div>
            <label htmlFor="classDescription" className="block text-sm font-medium text-slate-700 dark:text-slate-300">Description</label>
            <textarea
              id="classDescription"
              rows={3}
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              className="mt-1 block w-full px-3 py-2 bg-white dark:bg-slate-700 border border-slate-300 dark:border-slate-600 rounded-md shadow-sm"
              placeholder="A brief overview of the classroom's subject."
            />
          </div>
          {error && <p className="text-red-500 text-sm">{error}</p>}
        </div>

        <div className="mt-6 flex justify-end space-x-3">
          <button onClick={onClose} className="px-4 py-2 border border-slate-300 text-sm font-medium rounded-md text-slate-700 dark:text-slate-200 bg-white dark:bg-slate-700 hover:bg-slate-50 dark:hover:bg-slate-600">
            Cancel
          </button>
          <button onClick={handleSubmit} className="px-4 py-2 border border-transparent text-sm font-medium rounded-md shadow-sm text-white bg-sky-600 hover:bg-sky-700">
            Create Classroom
          </button>
        </div>
      </div>
    </div>
  );
};

export default CreateClassroomModal;
