// components/AIPerformanceReview.tsx
import React, { useState, useEffect } from 'react';
import { Question } from '../types';
import { generatePerformanceReview } from '../services/geminiService';
import SpinnerIcon from './icons/SpinnerIcon';

interface AIPerformanceReviewProps {
  questions: Question[];
  userAnswers: string[];
  score: number;
}

const AIPerformanceReview: React.FC<AIPerformanceReviewProps> = ({ questions, userAnswers, score }) => {
  const [review, setReview] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    const fetchReview = async () => {
      setIsLoading(true);
      try {
        const generatedReview = await generatePerformanceReview(questions, userAnswers, score);
        setReview(generatedReview);
      } catch (error) {
        console.error(error);
        setReview("Could not generate a review at this time.");
      } finally {
        setIsLoading(false);
      }
    };

    fetchReview();
  }, [questions, userAnswers, score]);

  return (
    <div className="p-4 bg-slate-50 dark:bg-slate-700/50 rounded-lg">
      <h4 className="text-lg font-semibold text-slate-800 dark:text-white mb-3">AI Performance Review</h4>
      {isLoading ? (
        <div className="flex flex-col items-center justify-center h-48">
            <SpinnerIcon className="w-8 h-8 text-sky-500" />
            <p className="mt-3 text-sm text-slate-500 dark:text-slate-400">Generating your personalized feedback...</p>
        </div>
      ) : (
        <div className="text-sm text-slate-600 dark:text-slate-300 whitespace-pre-wrap font-sans leading-relaxed">
            {review}
        </div>
      )}
    </div>
  );
};

export default AIPerformanceReview;

// frontend/src/app/components/ai-performance-review/ai-performance-review.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Question } from '../../types';
import { GeminiService } from '../../services/gemini.service';
import { SpinnerIconComponent } from '../icons/spinner-icon.component';

@Component({
  selector: 'app-ai-performance-review',
  standalone: true,
  imports: [CommonModule, SpinnerIconComponent],
  templateUrl: './ai-performance-review.component.html',
})
export class AIPerformanceReviewComponent implements OnInit {
  @Input() questions: Question[] = [];
  @Input() userAnswers: string[] = [];
  @Input() score: number = 0;

  review: string | null = null;
  isLoading = true;

  constructor(private geminiService: GeminiService) {}

  ngOnInit(): void {
    this.fetchReview();
  }

  fetchReview(): void {
    this.isLoading = true;
    this.geminiService.generatePerformanceReview(this.questions, this.userAnswers, this.score)
      .subscribe({
        next: (generatedReview) => {
          this.review = generatedReview;
          this.isLoading = false;
        },
        error: (error) => {
          console.error(error);
          this.review = "Could not generate a review at this time.";
          this.isLoading = false;
        }
      });
  }
}

<div class="p-4 bg-slate-50 dark:bg-slate-700/50 rounded-lg">
    <h4 class="text-lg font-semibold text-slate-800 dark:text-white mb-3">AI Performance Review</h4>
    <div *ngIf="isLoading; else reviewContent" class="flex flex-col items-center justify-center h-48">
        <app-spinner-icon [className]="'w-8 h-8 text-sky-500'"></app-spinner-icon>
        <p class="mt-3 text-sm text-slate-500 dark:text-slate-400">Generating your personalized feedback...</p>
    </div>
    <ng-template #reviewContent>
      <div class="text-sm text-slate-600 dark:text-slate-300 whitespace-pre-wrap font-sans leading-relaxed">
          {{ review }}
      </div>
    </ng-template>
</div>
